# Generated by Django 4.1.4 on 2023-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='mobile_no',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='authentication_admin',
        ),
        migrations.AlterModelTable(
            name='travel_agency',
            table='authentication_travel_agency',
        ),
        migrations.AlterModelTable(
            name='user',
            table='authentication_user',
        ),
    ]
