# Generated by Django 4.1.4 on 2023-03-01 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_admin_mobile_no_alter_admin_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_agency',
            name='mobile_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
