# Generated by Django 4.1.4 on 2023-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_travel_agency_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified_travel_agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(default=None, max_length=10, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('file', models.FileField(default='', upload_to='file')),
            ],
        ),
    ]
