# Generated by Django 4.1.4 on 2023-03-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_verified_travel_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=30)),
                ('form', models.CharField(max_length=30)),
                ('to', models.CharField(max_length=30)),
                ('total_seats', models.CharField(max_length=3)),
                ('window', models.CharField(max_length=3)),
                ('general', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=5)),
                ('bus_number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterModelTable(
            name='verified_travel_agency',
            table='authentication_verified_travel_agency',
        ),
    ]
