# Generated by Django 4.1.4 on 2023-03-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_schedule_alter_verified_travel_agency_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bus_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='verified_travel_agency',
            name='aadhar_no',
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='verified_travel_agency',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='verified_travel_agency',
            name='agency_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='verified_travel_agency',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='verified_travel_agency',
            name='password',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
