# Generated by Django 4.1.4 on 2023-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_schedule_bus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='agency_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
