# Generated by Django 4.1.4 on 2023-03-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_schedule_agency_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_agency',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
