# Generated by Django 4.1.4 on 2023-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_travel_agency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='agency_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
