# Generated by Django 4.1.4 on 2023-03-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_schedule_agency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(max_length=100)),
                ('b_from', models.CharField(max_length=30)),
                ('b_to', models.CharField(max_length=30)),
                ('Customer_name', models.CharField(default=None, max_length=100)),
                ('Agency_number', models.CharField(max_length=10)),
                ('bus_type', models.CharField(max_length=30)),
                ('Customer_number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('Seats', models.CharField(max_length=3)),
                ('amount', models.CharField(max_length=20)),
                ('seat_type', models.CharField(max_length=10)),
                ('Agency_name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('booking_time', models.TimeField()),
            ],
        ),
    ]
