# Generated by Django 4.1.4 on 2023-03-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.CharField(max_length=60),
        ),
    ]
