# Generated by Django 5.0.2 on 2024-03-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_agency',
            name='file',
            field=models.FileField(default=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='verified_travel_agency',
            name='file',
            field=models.FileField(default=True, upload_to='file'),
        ),
    ]
